[package]
name = "wambo"
description = "Wambo - All-in-one binary to convert decimal/bin/oct/hex + interpret data as i8-i64, u8-u64, and f32/f64."
version = "0.2.8"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
keywords = ["converter", "binary", "hex", "hexadecimal", "bytes"]
categories = []
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/wambo"
repository = "https://github.com/phip1611/wambo"
documentation = "https://docs.rs/wambo/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
derive_more = "0.99.11"
crossterm = "0.18.2"
fraction_list_fmt_align = "0.2.2"
# derive_more = { version = "0.99.11", features = ["derive"] }

